@API_HostAddress = https://localhost:5001

###Get weatherforecast
###https://localhost:5001/api/v1/weatherforecast
GET {{API_HostAddress}}/api/v1/weatherforecast

###Get all users
###https://localhost:5001/api/v1/users
GET {{API_HostAddress}}/api/v1/users

###Get user by Id
###https://localhost:5001/api/v1/users/1
GET {{API_HostAddress}}/api/v1/users/1
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhcmVuaXRhIiwibmJmIjoxNzI5NjkxNjMyLCJleHAiOjE3MzAyOTY0MzIsImlhdCI6MTcyOTY5MTYzMn0.DdcSCAbeX6RNZbZ_o1GpZlX9Y-BWSavVRFF6WGqu37AsNOicLJrrb6C-n6OywQ8wI3hidmkyOXcNHW7msWNdHA

###Get user by username
###https://localhost:5001/api/v1/users/arenita
GET {{API_HostAddress}}/api/v1/users/arenita
Authorization: Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiJhcmVuaXRhIiwibmJmIjoxNzMwMjA4MTg3LCJleHAiOjE3MzA4MTI5ODcsImlhdCI6MTczMDIwODE4N30.dZEcu6XKeZUylwHmOKmDcu6_DOpVzZDIgvpOz60OYaD0yOHRrgkIh0CY1EOW8LMSzJ3QUE-ucXS-LbTW5bqPtA


###Create a new user
###https://localhost:5001/api/v1/account/register
POST {{API_HostAddress}}/api/v1/account/register
Content-Type: application/json

{
    "username":"Leo",
    "password":"Wick"
}


###View what fields are required
###https://localhost:5001/api/v1/account/register
POST {{API_HostAddress}}/api/v1/account/register
Content-Type: application/json

{
}

###Login a user
###https://localhost:5001/api/v1/account/login
POST {{API_HostAddress}}/api/v1/account/login
Content-Type: application/json

{
    "username":"arenita",
    "password":"123456"
}

###Actualizar usuario
PUT {{API_HostAddress}}/api/v1/users/
Content-Type: application/json

{
    "Introduction":"Introduction updated", 
    "LookingFor":"Looking For updated", 
    "Interests":"Interest updated", 
    "City":"City updated",
    "Country":"Country updated", 
}

###Get Server error
###https://localhost:5001/api/v1/Buggy/server-error
GET {{API_HostAddress}}/api/v1/Buggy/server-error

###Get bad request
###https://localhost:5001/api/v1/Buggy/bad-request
GET {{API_HostAddress}}/api/v1/Buggy/bad-request

server-error