@API_HostAddress = https://localhost:5001

###Get weatherforecast
###https://localhost:5001/api/v1/weatherforecast
GET {{API_HostAddress}}/api/v1/weatherforecast

###Get all users
###https://localhost:5001/api/v1/users
GET {{API_HostAddress}}/api/v1/users

###Get user by Id
###https://localhost:5001/api/v1/users/1
GET {{API_HostAddress}}/api/v1/users/1

###Create a new user
###https://localhost:5001/api/v1/account/register
POST {{API_HostAddress}}/api/v1/account/register
Content-Type: application/json

{
    "username":"John",
    "password":"Wick"
}